spring.application.name=payment-service

server.port=${PORT:8086}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP:payment-service-group}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.fabriciosanches.shared.events
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.kafka.topic.pedido-realizado=${KAFKA_TOPIC_PEDIDO_REALIZADO:PEDIDO_REALIZADO}
app.kafka.topic.pagamento-confirmado=${KAFKA_TOPIC_PAGAMENTO_CONFIRMADO:PAGAMENTO_CONFIRMADO}
app.kafka.topic.pagamento-negado=${KAFKA_TOPIC_PAGAMENTO_NEGADO:PAGAMENTO_NEGADO}

